bulk_insert_data = []
bulk_insert_data << Contest.new(nth:  1, year: 1988, name: "乾電池カー・スピードレース")
bulk_insert_data << Contest.new(nth:  2, year: 1989, name: "オクトパスフットボール")
bulk_insert_data << Contest.new(nth:  3, year: 1990, name: "ニュートロンスター")
bulk_insert_data << Contest.new(nth:  4, year: 1991, name: "ホットタワー")
bulk_insert_data << Contest.new(nth:  5, year: 1992, name: "ミステリーサークル")
bulk_insert_data << Contest.new(nth:  6, year: 1993, name: "ステップダンス")
bulk_insert_data << Contest.new(nth:  7, year: 1994, name: "スペースフライヤー")
bulk_insert_data << Contest.new(nth:  8, year: 1995, name: "ドリームタワー")
bulk_insert_data << Contest.new(nth:  9, year: 1996, name: "テクノカウボーイ")
bulk_insert_data << Contest.new(nth: 10, year: 1997, name: "花開蝶来")
bulk_insert_data << Contest.new(nth: 11, year: 1998, name: "生命上陸")
bulk_insert_data << Contest.new(nth: 12, year: 1999, name: "Jump To The Future")
bulk_insert_data << Contest.new(nth: 13, year: 2000, name: "ミレニアムメッセージ")
bulk_insert_data << Contest.new(nth: 14, year: 2001, name: "Happy Birthday 39")
bulk_insert_data << Contest.new(nth: 15, year: 2002, name: "プロジェクトBOX")
bulk_insert_data << Contest.new(nth: 16, year: 2003, name: "鼎")
bulk_insert_data << Contest.new(nth: 17, year: 2004, name: "マーズラッシュ")
bulk_insert_data << Contest.new(nth: 18, year: 2005, name: "大運動会")
bulk_insert_data << Contest.new(nth: 19, year: 2006, name: "ふるさと自慢特急便")
bulk_insert_data << Contest.new(nth: 20, year: 2007, name: "風林火山 ロボット騎馬戦")
bulk_insert_data << Contest.new(nth: 21, year: 2008, name: "ROBO－EVOLUTION 生命大進化")
bulk_insert_data << Contest.new(nth: 22, year: 2009, name: "DANCIN' COUPLE")
bulk_insert_data << Contest.new(nth: 23, year: 2010, name: "激走! ロボ力車")
bulk_insert_data << Contest.new(nth: 24, year: 2011, name: "ロボ・ボウル")
bulk_insert_data << Contest.new(nth: 25, year: 2012, name: "ベスト・ペット")
bulk_insert_data << Contest.new(nth: 26, year: 2013, name: "Shall We Jump?")
bulk_insert_data << Contest.new(nth: 27, year: 2014, name: "出前迅速")
bulk_insert_data << Contest.new(nth: 28, year: 2015, name: "輪花繚乱")
bulk_insert_data << Contest.new(nth: 29, year: 2016, name: "ロボット・ニューフロンティア")
bulk_insert_data << Contest.new(nth: 30, year: 2017, name: "大江戸ロボット忍法帳")
Contest.import bulk_insert_data
