# 各賞の詳細な調査が必要。
PrizeType.create(type: 1, name: "優勝")
PrizeType.create(type: 2, name: "準優勝")
PrizeType.create(type: 3, name: "ベスト４")

PrizeType.create(type: 11, name: "アイデア賞")
PrizeType.create(type: 12, name: "アイデア倒れ賞")
PrizeType.create(type: 13, name: "技術賞")
PrizeType.create(type: 14, name: "大賞")
PrizeType.create(type: 15, name: "ベストデザイン賞")
PrizeType.create(type: 16, name: "芸術賞")
PrizeType.create(type: 17, name: "デザイン賞")

PrizeType.create(type: 21, name: "完全燃賞")
PrizeType.create(type: 22, name: "優秀賞")

PrizeType.create(type: 31, name: "応援団賞")
PrizeType.create(type: 32, name: "ベストビデオ賞")

PrizeType.create(type: 41, name: "ふるさと自慢賞")
PrizeType.create(type: 42, name: "風林火山賞")
PrizeType.create(type: 43, name: "生命大進化賞")
PrizeType.create(type: 44, name: "ベストカップル賞")
PrizeType.create(type: 45, name: "激走賞")
PrizeType.create(type: 46, name: "ロボ・ボウル賞")
PrizeType.create(type: 47, name: "ベスト・ペット賞")
PrizeType.create(type: 48, name: "シャル・ウィ・ジャンプ賞")
PrizeType.create(type: 49, name: "出前迅速賞")

PrizeType.create(type: 51, name: "特別賞")
PrizeType.create(type: 52, name: "省エネルギーセンター賞")
PrizeType.create(type: 53, name: "電気事業連合会賞")

PrizeType.create(type: 61, name: "特別賞（本田技研工業株式会社）")
PrizeType.create(type: 62, name: "特別賞（電気事業連合会）")
PrizeType.create(type: 63, name: "特別賞（マブチモーター株式会社）")
PrizeType.create(type: 64, name: "特別賞（ソリッドワークスジャパン株式会社）")
PrizeType.create(type: 65, name: "特別賞（株式会社安川電機）")
PrizeType.create(type: 66, name: "特別賞（東京エレクトロンＦＥ株式会社）")
PrizeType.create(type: 67, name: "特別賞（田中貴金属グル－プ）")
PrizeType.create(type: 68, name: "特別賞（ローム株式会社）")
