# 各賞の詳細な調査が必要。
Prize.create(kind: 1, name: "優勝")
Prize.create(kind: 2, name: "準優勝")
Prize.create(kind: 3, name: "ベスト４")

Prize.create(kind: 11, name: "アイデア賞")
Prize.create(kind: 12, name: "アイデア倒れ賞")
Prize.create(kind: 13, name: "技術賞")
Prize.create(kind: 14, name: "大賞")
Prize.create(kind: 15, name: "ベストデザイン賞")
Prize.create(kind: 16, name: "芸術賞")
Prize.create(kind: 17, name: "デザイン賞")

Prize.create(kind: 21, name: "完全燃賞")
Prize.create(kind: 22, name: "優秀賞")

Prize.create(kind: 31, name: "応援団賞")
Prize.create(kind: 32, name: "ベストビデオ賞")

Prize.create(kind: 41, name: "ふるさと自慢賞")
Prize.create(kind: 42, name: "風林火山賞")
Prize.create(kind: 43, name: "生命大進化賞")
Prize.create(kind: 44, name: "ベストカップル賞")
Prize.create(kind: 45, name: "激走賞")
Prize.create(kind: 46, name: "ロボ・ボウル賞")
Prize.create(kind: 47, name: "ベスト・ペット賞")
Prize.create(kind: 48, name: "シャル・ウィ・ジャンプ賞")
Prize.create(kind: 49, name: "出前迅速賞")

Prize.create(kind: 51, name: "特別賞")
Prize.create(kind: 52, name: "省エネルギーセンター賞")
Prize.create(kind: 53, name: "電気事業連合会賞")

Prize.create(kind: 61, name: "特別賞（本田技研工業株式会社）")
Prize.create(kind: 62, name: "特別賞（電気事業連合会）")
Prize.create(kind: 63, name: "特別賞（マブチモーター株式会社）")
Prize.create(kind: 64, name: "特別賞（ソリッドワークスジャパン株式会社）")
Prize.create(kind: 65, name: "特別賞（株式会社安川電機）")
Prize.create(kind: 66, name: "特別賞（東京エレクトロンＦＥ株式会社）")
Prize.create(kind: 67, name: "特別賞（田中貴金属グル－プ）")
Prize.create(kind: 68, name: "特別賞（ローム株式会社）")
