region = Region.create(name: "北海道")
Campus.create(region: region, code: 1010, name: "旭川工業高等専門学校", abbreviation: "旭川", latitude: 43.812361, longitude: 142.353665)
Campus.create(region: region, code: 1020, name: "釧路工業高等専門学校", abbreviation: "釧路", latitude: 43.01606, longitude: 144.26112)
Campus.create(region: region, code: 1030, name: "札幌市立高等専門学校", abbreviation: "札幌", latitude: 42.995078, longitude: 141.374753)
Campus.create(region: region, code: 1040, name: "苫小牧工業高等専門学校", abbreviation: "苫小牧", latitude: 42.623737, longitude: 141.495271)
Campus.create(region: region, code: 1050, name: "函館工業高等専門学校", abbreviation: "函館", latitude: 41.783736, longitude: 140.802575)
region = Region.create(name: "東北")
Campus.create(region: region, code: 2060, name: "八戸工業高等専門学校", abbreviation: "八戸", latitude: 40.491151, longitude: 141.448176)
Campus.create(region: region, code: 2070, name: "秋田工業高等専門学校", abbreviation: "秋田", latitude: 39.772519, longitude: 140.079455)
Campus.create(region: region, code: 2080, name: "一関高等専門学校", abbreviation: "一関", latitude: 38.92378, longitude: 141.107268)
Campus.create(region: region, code: 2090, name: "鶴岡工業高等専門学校", abbreviation: "鶴岡", latitude: 38.709793, longitude: 139.797455)
Campus.create(region: region, code: 2100, name: "仙台高等専門学校広瀬キャンパス", abbreviation: "仙台広瀬", latitude: 38.275882, longitude: 140.751881)
Campus.create(region: region, code: 2110, name: "仙台高等専門学校名取キャンパス", abbreviation: "仙台名取", latitude: 38.167587, longitude: 140.865005)
Campus.create(region: region, code: 2120, name: "福島工業高等専門学校", abbreviation: "福島", latitude: 37.033047, longitude: 140.889339)
region = Region.create(name: "関東甲信越")
Campus.create(region: region, code: 3130, name: "長岡工業高等専門学校", abbreviation: "長岡", latitude: 37.432737, longitude: 138.889285)
Campus.create(region: region, code: 3140, name: "長野工業高等専門学校", abbreviation: "長野", latitude: 36.678267, longitude: 138.233794)
Campus.create(region: region, code: 3150, name: "茨城工業高等専門学校", abbreviation: "茨城", latitude: 36.400339, longitude: 140.551048)
Campus.create(region: region, code: 3160, name: "群馬工業高等専門学校", abbreviation: "群馬", latitude: 36.377098, longitude: 139.024158)
Campus.create(region: region, code: 3170, name: "小山工業高等専門学校", abbreviation: "小山", latitude: 36.318303, longitude: 139.842072)
Campus.create(region: region, code: 3180, name: "東京都立産業技術高等専門学校荒川キャンパス", abbreviation: "産技荒川", latitude: 35.734483, longitude: 139.809449)
Campus.create(region: region, code: 3190, name: "東京工業高等専門学校", abbreviation: "東京", latitude: 35.639265, longitude: 139.298829)
Campus.create(region: region, code: 3200, name: "東京都立産業技術高等専門学校品川キャンパス", abbreviation: "産技品川", latitude: 35.606994, longitude: 139.749091)
Campus.create(region: region, code: 3210, name: "サレジオ工業高等専門学校", abbreviation: "サレジオ", latitude: 35.605284, longitude: 139.357938)
Campus.create(region: region, code: 3220, name: "桐蔭学園工業高等専門学校", abbreviation: "桐蔭", latitude: 35.566209, longitude: 139.518228)
Campus.create(region: region, code: 3230, name: "木更津工業高等専門学校", abbreviation: "木更津", latitude: 35.384422, longitude: 139.955556)
region = Region.create(name: "東海北陸")
Campus.create(region: region, code: 4240, name: "富山高等専門学校射水キャンパス", abbreviation: "富山射水", latitude: 36.758859, longitude: 137.158814)
Campus.create(region: region, code: 4250, name: "石川工業高等専門学校", abbreviation: "石川", latitude: 36.662102, longitude: 136.73834)
Campus.create(region: region, code: 4260, name: "富山高等専門学校本郷キャンパス", abbreviation: "富山本郷", latitude: 36.650966, longitude: 137.24397)
Campus.create(region: region, code: 4270, name: "金沢工業高等専門学校", abbreviation: "金沢", latitude: 36.532542, longitude: 136.62939)
Campus.create(region: region, code: 4280, name: "福井工業高等専門学校", abbreviation: "福井", latitude: 35.936801, longitude: 136.171006)
Campus.create(region: region, code: 4290, name: "岐阜工業高等専門学校", abbreviation: "岐阜", latitude: 35.44707, longitude: 136.672609)
Campus.create(region: region, code: 4300, name: "沼津工業高等専門学校", abbreviation: "沼津", latitude: 35.135838, longitude: 138.883871)
Campus.create(region: region, code: 4310, name: "豊田工業高等専門学校", abbreviation: "豊田", latitude: 35.103347, longitude: 137.148587)
Campus.create(region: region, code: 4320, name: "鈴鹿工業高等専門学校", abbreviation: "鈴鹿", latitude: 34.850201, longitude: 136.580722)
Campus.create(region: region, code: 4330, name: "鳥羽商船高等専門学校", abbreviation: "鳥羽商船", latitude: 34.482261, longitude: 136.824792)
region = Region.create(name: "近畿")
Campus.create(region: region, code: 5340, name: "舞鶴工業高等専門学校", abbreviation: "舞鶴", latitude: 35.495723, longitude: 135.4405)
Campus.create(region: region, code: 5350, name: "大阪府立大学工業高等専門学校", abbreviation: "大阪府大", latitude: 34.77042, longitude: 135.629576)
Campus.create(region: region, code: 5360, name: "明石工業高等専門学校", abbreviation: "明石", latitude: 34.695109, longitude: 134.902233)
Campus.create(region: region, code: 5370, name: "神戸市立工業高等専門学校", abbreviation: "神戸", latitude: 34.679577, longitude: 135.067222)
Campus.create(region: region, code: 5380, name: "奈良工業高等専門学校", abbreviation: "奈良", latitude: 34.648211, longitude: 135.75854)
Campus.create(region: region, code: 5390, name: "近畿大学工業高等専門学校", abbreviation: "近大", latitude: 34.614416, longitude: 136.122642)
Campus.create(region: region, code: 5400, name: "和歌山工業高等専門学校", abbreviation: "和歌山", latitude: 33.833931, longitude: 135.177709)
region = Region.create(name: "中国")
Campus.create(region: region, code: 6410, name: "松江工業高等専門学校", abbreviation: "松江", latitude: 35.496114, longitude: 133.025828)
Campus.create(region: region, code: 6420, name: "米子工業高等専門学校", abbreviation: "米子", latitude: 35.455172, longitude: 133.289691)
Campus.create(region: region, code: 6430, name: "津山工業高等専門学校", abbreviation: "津山", latitude: 35.08118, longitude: 134.013034)
Campus.create(region: region, code: 6440, name: "広島商船高等専門学校", abbreviation: "広島商船", latitude: 34.253456, longitude: 132.904204)
Campus.create(region: region, code: 6450, name: "呉工業高等専門学校", abbreviation: "呉", latitude: 34.232232, longitude: 132.603293)
Campus.create(region: region, code: 6460, name: "徳山工業高等専門学校", abbreviation: "徳山", latitude: 34.052226, longitude: 131.846532)
Campus.create(region: region, code: 6470, name: "宇部工業高等専門学校", abbreviation: "宇部", latitude: 33.955298, longitude: 131.274858)
Campus.create(region: region, code: 6480, name: "大島商船高等専門学校", abbreviation: "大島商船", latitude: 33.927945, longitude: 132.190871)
region = Region.create(name: "四国")
Campus.create(region: region, code: 7490, name: "香川高等専門学校高松キャンパス", abbreviation: "香川高松", latitude: 34.311174, longitude: 134.010801)
Campus.create(region: region, code: 7500, name: "弓削商船高等専門学校", abbreviation: "弓削商船", latitude: 34.253254, longitude: 133.207525)
Campus.create(region: region, code: 7510, name: "香川高等専門学校詫間キャンパス", abbreviation: "香川詫間", latitude: 34.235344, longitude: 133.63487)
Campus.create(region: region, code: 7520, name: "新居浜工業高等専門学校", abbreviation: "新居浜", latitude: 33.960793, longitude: 133.291163)
Campus.create(region: region, code: 7530, name: "阿南工業高等専門学校", abbreviation: "阿南", latitude: 33.898252, longitude: 134.667567)
Campus.create(region: region, code: 7540, name: "高知工業高等専門学校", abbreviation: "高知", latitude: 33.546102, longitude: 133.678696)
region = Region.create(name: "九州沖縄")
Campus.create(region: region, code: 8550, name: "北九州工業高等専門学校", abbreviation: "北九州", latitude: 33.81649, longitude: 130.871816)
Campus.create(region: region, code: 8560, name: "久留米工業高等専門学校", abbreviation: "久留米", latitude: 33.336316, longitude: 130.510767)
Campus.create(region: region, code: 8570, name: "大分工業高等専門学校", abbreviation: "大分", latitude: 33.232684, longitude: 131.650714)
Campus.create(region: region, code: 8580, name: "佐世保工業高等専門学校", abbreviation: "佐世保", latitude: 33.149891, longitude: 129.748108)
Campus.create(region: region, code: 8590, name: "有明工業高等専門学校", abbreviation: "有明", latitude: 33.00373, longitude: 130.473949)
Campus.create(region: region, code: 8600, name: "熊本高等専門学校熊本キャンパス", abbreviation: "熊本熊本", latitude: 32.876771, longitude: 130.747864)
Campus.create(region: region, code: 8610, name: "熊本高等専門学校八代キャンパス", abbreviation: "熊本八代", latitude: 32.476232, longitude: 130.607669)
Campus.create(region: region, code: 8620, name: "都城工業高等専門学校", abbreviation: "都城", latitude: 31.760844, longitude: 131.079678)
Campus.create(region: region, code: 8630, name: "鹿児島工業高等専門学校", abbreviation: "鹿児島", latitude: 31.73126, longitude: 130.728807)
Campus.create(region: region, code: 8640, name: "沖縄工業高等専門学校", abbreviation: "沖縄", latitude: 26.526144, longitude: 128.031318)
region = Region.create(name: "他")
Campus.create(region: region, code: 9650, name: "Electronic Engineering Polytechnic Institute of Surabaya", abbreviation: "スラバヤ", latitude: -7.276785, longitude: 112.794882)

Contest.create(nth:  1, year: 1988, name: "乾電池カー・スピードレース")
Contest.create(nth:  2, year: 1989, name: "オクトパスフットボール")
Contest.create(nth:  3, year: 1990, name: "ニュートロンスター")
Contest.create(nth:  4, year: 1991, name: "ホットタワー")
Contest.create(nth:  5, year: 1992, name: "ミステリーサークル")
Contest.create(nth:  6, year: 1993, name: "ステップダンス")
Contest.create(nth:  7, year: 1994, name: "スペースフライヤー")
Contest.create(nth:  8, year: 1995, name: "ドリームタワー")
Contest.create(nth:  9, year: 1996, name: "テクノカウボーイ")
Contest.create(nth: 10, year: 1997, name: "花開蝶来")
Contest.create(nth: 11, year: 1998, name: "生命上陸")
Contest.create(nth: 12, year: 1999, name: "Jump To The Future")
Contest.create(nth: 13, year: 2000, name: "ミレニアムメッセージ")
Contest.create(nth: 14, year: 2001, name: "Happy Birthday 39")
Contest.create(nth: 15, year: 2002, name: "プロジェクトBOX")
Contest.create(nth: 16, year: 2003, name: "鼎")
Contest.create(nth: 17, year: 2004, name: "マーズラッシュ")
Contest.create(nth: 18, year: 2005, name: "大運動会")
Contest.create(nth: 19, year: 2006, name: "ふるさと自慢特急便")
Contest.create(nth: 20, year: 2007, name: "風林火山 ロボット騎馬戦")
Contest.create(nth: 21, year: 2008, name: "ROBO－EVOLUTION 生命大進化")
Contest.create(nth: 22, year: 2009, name: "DANCIN' COUPLE")
Contest.create(nth: 23, year: 2010, name: "激走! ロボ力車")
Contest.create(nth: 24, year: 2011, name: "ロボ・ボウル")
Contest.create(nth: 25, year: 2012, name: "ベスト・ペット")
Contest.create(nth: 26, year: 2013, name: "Shall We Jump?")
Contest.create(nth: 27, year: 2014, name: "出前迅速")
Contest.create(nth: 28, year: 2015, name: "輪花繚乱")
Contest.create(nth: 29, year: 2016, name: "ロボット・ニューフロンティア")

Robot.create(contest: Contest.find_by(nth:  2), campus: Campus.find_by(abbreviation: "旭川"), name: "ビッグシューター", kana: "ビッグシューター")
Robot.create(contest: Contest.find_by(nth:  3), campus: Campus.find_by(abbreviation: "旭川"), name: "マジックカーペット", kana: "マジックカーペット")
Robot.create(contest: Contest.find_by(nth:  4), campus: Campus.find_by(abbreviation: "旭川"), name: "Fly Swatter", kana: "フライスワッター")
Robot.create(contest: Contest.find_by(nth:  4), campus: Campus.find_by(abbreviation: "旭川"), name: "セブンボンバー", kana: "セブンボンバー")
Robot.create(contest: Contest.find_by(nth:  5), campus: Campus.find_by(abbreviation: "旭川"), name: "春光台にそそり立つ", kana: "シュンコウダイニソソリタツ")
Robot.create(contest: Contest.find_by(nth:  5), campus: Campus.find_by(abbreviation: "旭川"), name: "ANCoT16", kana: "アンコットシックスティーン")
Robot.create(contest: Contest.find_by(nth:  6), campus: Campus.find_by(abbreviation: "旭川"), name: "かっとびチュー太", kana: "カットビチュータ")
Robot.create(contest: Contest.find_by(nth:  6), campus: Campus.find_by(abbreviation: "旭川"), name: "大雪山ジムカデ号", kana: "タイセツザンジムカデゴウ")
Robot.create(contest: Contest.find_by(nth:  7), campus: Campus.find_by(abbreviation: "旭川"), name: "アンモナイト", kana: "アンモナイト")
Robot.create(contest: Contest.find_by(nth:  7), campus: Campus.find_by(abbreviation: "旭川"), name: "大雪山ウスバキチョウ", kana: "オオユキヤマウスバキチョウ")
Robot.create(contest: Contest.find_by(nth:  8), campus: Campus.find_by(abbreviation: "旭川"), name: "ビューティフルシューター", kana: "ビューティフルシューター")
Robot.create(contest: Contest.find_by(nth:  8), campus: Campus.find_by(abbreviation: "旭川"), name: "コマクサ", kana: "コマクサ")
Robot.create(contest: Contest.find_by(nth:  9), campus: Campus.find_by(abbreviation: "旭川"), name: "らいとにんぐ", kana: "ライトニング")
Robot.create(contest: Contest.find_by(nth:  9), campus: Campus.find_by(abbreviation: "旭川"), name: "北乃麒麟", kana: "キタノキリン")
Robot.create(contest: Contest.find_by(nth: 10), campus: Campus.find_by(abbreviation: "旭川"), name: "SPEEDY WONDER", kana: "スピーディーワンダー")
Robot.create(contest: Contest.find_by(nth: 10), campus: Campus.find_by(abbreviation: "旭川"), name: "HAPPY1号", kana: "ハッピーイチゴウ")
Robot.create(contest: Contest.find_by(nth: 11), campus: Campus.find_by(abbreviation: "旭川"), name: "MACH-CHAN1号", kana: "マッハチャンイチゴウ")
Robot.create(contest: Contest.find_by(nth: 11), campus: Campus.find_by(abbreviation: "旭川"), name: "ジムカデJr.号", kana: "ジムカデジュニアゴウ")
Robot.create(contest: Contest.find_by(nth: 12), campus: Campus.find_by(abbreviation: "旭川"), name: "Blitz Schnell", kana: "ブリッツシュネル")
Robot.create(contest: Contest.find_by(nth: 12), campus: Campus.find_by(abbreviation: "旭川"), name: "Safety Slope", kana: "セイフティースロープ")
Robot.create(contest: Contest.find_by(nth: 13), campus: Campus.find_by(abbreviation: "旭川"), name: "大車輪", kana: "ダイシャリン")
Robot.create(contest: Contest.find_by(nth: 13), campus: Campus.find_by(abbreviation: "旭川"), name: "Be Shorten", kana: "ビーショーテン")
Robot.create(contest: Contest.find_by(nth: 14), campus: Campus.find_by(abbreviation: "旭川"), name: "BELL FLOWER", kana: "ベルフラワー")
Robot.create(contest: Contest.find_by(nth: 14), campus: Campus.find_by(abbreviation: "旭川"), name: "grasp", kana: "グラスプ")
Robot.create(contest: Contest.find_by(nth: 15), campus: Campus.find_by(abbreviation: "旭川"), name: "Master Plan", kana: "マスタープラン")
Robot.create(contest: Contest.find_by(nth: 15), campus: Campus.find_by(abbreviation: "旭川"), name: "the jail", kana: "ザジェイル")
Robot.create(contest: Contest.find_by(nth: 16), campus: Campus.find_by(abbreviation: "旭川"), name: "Untyred", kana: "アンタイヤド")
Robot.create(contest: Contest.find_by(nth: 16), campus: Campus.find_by(abbreviation: "旭川"), name: "Clock Ruler", kana: "クロックルーラー")
Robot.create(contest: Contest.find_by(nth: 17), campus: Campus.find_by(abbreviation: "旭川"), name: "Sleip", kana: "スレイプ")
Robot.create(contest: Contest.find_by(nth: 17), campus: Campus.find_by(abbreviation: "旭川"), name: "Cosmos", kana: "コスモス")
Robot.create(contest: Contest.find_by(nth: 18), campus: Campus.find_by(abbreviation: "旭川"), name: "パッション!!", kana: "パッション")
Robot.create(contest: Contest.find_by(nth: 18), campus: Campus.find_by(abbreviation: "旭川"), name: "concord", kana: "コンコード")
Robot.create(contest: Contest.find_by(nth: 19), campus: Campus.find_by(abbreviation: "旭川"), name: "セタ", kana: "セタ")
Robot.create(contest: Contest.find_by(nth: 19), campus: Campus.find_by(abbreviation: "旭川"), name: "初雪", kana: "ハツユキ")
Robot.create(contest: Contest.find_by(nth: 20), campus: Campus.find_by(abbreviation: "旭川"), name: "NOTEC", kana: "ノテック")
Robot.create(contest: Contest.find_by(nth: 20), campus: Campus.find_by(abbreviation: "旭川"), name: "ＧＬＡＤＩＯＬＵＳ", kana: "グラディオラス")
Robot.create(contest: Contest.find_by(nth: 21), campus: Campus.find_by(abbreviation: "旭川"), name: "KAMUI", kana: "カムイ")
Robot.create(contest: Contest.find_by(nth: 21), campus: Campus.find_by(abbreviation: "旭川"), name: "TRIVIOS", kana: "トリヴィオス")
Robot.create(contest: Contest.find_by(nth: 22), campus: Campus.find_by(abbreviation: "旭川"), name: "北の海から", kana: "キタノウミカラ")
Robot.create(contest: Contest.find_by(nth: 22), campus: Campus.find_by(abbreviation: "旭川"), name: "ＫＡＧＵＹＡ", kana: "カグヤ")
Robot.create(contest: Contest.find_by(nth: 23), campus: Campus.find_by(abbreviation: "旭川"), name: "7Walk", kana: "セブンウォーク")
Robot.create(contest: Contest.find_by(nth: 23), campus: Campus.find_by(abbreviation: "旭川"), name: "ｒｅｖｌｉｓ", kana: "レヴリス")
Robot.create(contest: Contest.find_by(nth: 24), campus: Campus.find_by(abbreviation: "旭川"), name: "ｓｉｄｅ　ＷＩＮｄｅｒ", kana: "サイドワインダー")
Robot.create(contest: Contest.find_by(nth: 24), campus: Campus.find_by(abbreviation: "旭川"), name: "ＸｉｇＸａｇ", kana: "ジグザグ")
Robot.create(contest: Contest.find_by(nth: 25), campus: Campus.find_by(abbreviation: "旭川"), name: "ぽちべろす", kana: "ポチベロス")
Robot.create(contest: Contest.find_by(nth: 25), campus: Campus.find_by(abbreviation: "旭川"), name: "旭", kana: "キュウビ")
Robot.create(contest: Contest.find_by(nth: 26), campus: Campus.find_by(abbreviation: "旭川"), name: "JANPY", kana: "ジャンピー")
Robot.create(contest: Contest.find_by(nth: 26), campus: Campus.find_by(abbreviation: "旭川"), name: "カメニカルズ", kana: "カメニカルズ")
Robot.create(contest: Contest.find_by(nth: 27), campus: Campus.find_by(abbreviation: "旭川"), name: "ベルーガ", kana: "ベルーガ")
Robot.create(contest: Contest.find_by(nth: 27), campus: Campus.find_by(abbreviation: "旭川"), name: "蒸龍", kana: "セイロン")
Robot.create(contest: Contest.find_by(nth: 28), campus: Campus.find_by(abbreviation: "旭川"), name: "Orthrows", kana: "オルトロス")
Robot.create(contest: Contest.find_by(nth: 28), campus: Campus.find_by(abbreviation: "旭川"), name: "―Umbrella―", kana: "アンブレラ")
Robot.create(contest: Contest.find_by(nth: 29), campus: Campus.find_by(abbreviation: "旭川"), name: "HYDRA", kana: "ヒュドラ", team: "A")
Robot.create(contest: Contest.find_by(nth: 29), campus: Campus.find_by(abbreviation: "旭川"), name: "sucfaro、sucforte", kana: "サクファロ　サクフォート", team: "B")

ContestEntry.create(nth:  1, school: 12, campus: 12, team: 12)
ContestEntry.create(nth:  2, school: 20, campus: 20, team: 20)
ContestEntry.create(nth:  3, school: 62, campus: 62, team: 62)
ContestEntry.create(nth:  4, school: 63, campus: 63, team: 125)
ContestEntry.create(nth:  5, school: 63, campus: 63, team: 124)
ContestEntry.create(nth:  6, school: 62, campus: 62, team: 124)
ContestEntry.create(nth:  7, school: 62, campus: 62, team: 123)
ContestEntry.create(nth:  8, school: 62, campus: 62, team: 124)
ContestEntry.create(nth:  9, school: 62, campus: 62, team: 124)
ContestEntry.create(nth: 10, school: 62, campus: 62, team: 124)
ContestEntry.create(nth: 11, school: 62, campus: 62, team: 122)
ContestEntry.create(nth: 12, school: 62, campus: 62, team: 124)
ContestEntry.create(nth: 13, school: 62, campus: 62, team: 124)
ContestEntry.create(nth: 14, school: 62, campus: 62, team: 124)
ContestEntry.create(nth: 15, school: 62, campus: 62, team: 124)
ContestEntry.create(nth: 16, school: 62, campus: 62, team: 123)
ContestEntry.create(nth: 17, school: 63, campus: 63, team: 126)
ContestEntry.create(nth: 18, school: 63, campus: 63, team: 126)
ContestEntry.create(nth: 19, school: 61, campus: 62, team: 124)
ContestEntry.create(nth: 20, school: 61, campus: 62, team: 124)
ContestEntry.create(nth: 21, school: 61, campus: 62, team: 124)
ContestEntry.create(nth: 22, school: 57, campus: 62, team: 124)
ContestEntry.create(nth: 23, school: 57, campus: 62, team: 124)
ContestEntry.create(nth: 24, school: 57, campus: 62, team: 124)
ContestEntry.create(nth: 25, school: 57, campus: 62, team: 124)
ContestEntry.create(nth: 26, school: 57, campus: 62, team: 124)
ContestEntry.create(nth: 27, school: 57, campus: 62, team: 124)
ContestEntry.create(nth: 28, school: 57, campus: 62, team: 124)
ContestEntry.create(nth: 29, school: 57, campus: 62, team: 124)
